n1=input("Enter your number:" )
print(n1)
n2=input("Enter your number:" )
print(n2)
n3=input("Enter your number:" )
print(n3)
n4=input("Enter your number:" )
print(n4)
n5=input("Enter your number:" )
print(n5)
n6=input("Enter your number:" )
print(n6)
n7=input("Enter your number:" )
print(n7)
n8=input("Enter your number:" )
print(n8)

set= {n1,n2,n3,n4,n5,n6,n7,n8}
print(set)