d= {}
name=input("Enter your name:")
lang=input("Enter your fav language:")
d.update({name:lang})
name=input("Enter your name:")
lang=input("Enter your fav language:")
d.update({name:lang})
name=input("Enter your name:")
lang=input("Enter your fav language:")
d.update({name:lang})
name=input("Enter your name:")
lang=input("Enter your fav language:")
d.update({name:lang})
print(d)